// ==UserScript==
// @name           M365 Copilot — token → VS Code
// @name:es        M365 Copilot — token → VS Code
// @namespace      https://github.com/cristiancastineiras/M365CopilotVSCode
// @version        2.0.0
// @description    Captures your Microsoft 365 Copilot session token and sends it to the M365 Copilot extension for VS Code automatically (or lets you copy it).
// @description:es Captura el token de tu sesión de Microsoft 365 Copilot y lo envía a la extensión M365 Copilot de VS Code automáticamente (o te deja copiarlo).
// @author         Cristian Castineiras
// @homepageURL    https://github.com/cristiancastineiras/M365CopilotVSCode
// @supportURL     https://github.com/cristiancastineiras/M365CopilotVSCode/issues
// @updateURL      https://raw.githubusercontent.com/cristiancastineiras/M365CopilotVSCode/main/extensiones/vscode/m365copilot-token.user.js
// @downloadURL    https://raw.githubusercontent.com/cristiancastineiras/M365CopilotVSCode/main/extensiones/vscode/m365copilot-token.user.js
// @run-at         document-start
// @match          https://m365.cloud.microsoft/*
// @match          https://*.cloud.microsoft/*
// @match          https://www.office.com/*
// @match          https://outlook.office.com/*
// @match          https://teams.microsoft.com/*
// @grant          GM_getValue
// @grant          GM_setValue
// @grant          GM_addValueChangeListener
// @grant          GM_setClipboard
// @grant          GM_xmlhttpRequest
// @grant          GM_registerMenuCommand
// @grant          unsafeWindow
// @connect        localhost
// ==/UserScript==

// GENERATED by extensiones/vscode/scripts/build-userscript.mjs from userscript/main.ts
// and @m365copilot/core — do not edit by hand: run `pnpm build` in extensiones/vscode.

(function() {

//#region ../../packages/core/dist/constants.js
/**
	* Contrato de red entre la extensión de navegador, los userscripts de
	* Tampermonkey y el servidor local de la extensión de VS Code.
	*
	* Es la ÚNICA fuente de verdad: si el puerto o la ruta se desincronizan, el
	* token deja de sincronizarse silenciosamente (exactamente el bug que había
	* cuando el navegador apuntaba a 39283/profile y el servidor escuchaba en
	* 51827/token). Manténlo aquí y consúmelo desde ambos lados.
	*/
	const TOKEN_SERVER_HOST = "localhost";
	const TOKEN_SERVER_PORT = 51827;
	const TOKEN_SERVER_URL = `http://${TOKEN_SERVER_HOST}:${TOKEN_SERVER_PORT}`;
	/** Ruta donde el servidor de VS Code recibe el perfil/token (POST). */
	const TOKEN_ENDPOINT_PATH = "/token";
	/** Ruta de health-check para saber si VS Code está escuchando (GET). */
	const HEALTH_ENDPOINT_PATH = "/health";
	/**
	* Web de M365 Copilot: donde se captura el token. La extensión de navegador
	* abre aquí una pestaña en segundo plano para renovarlo, y la de VS Code la
	* ofrece cuando el token falta o caduca.
	*/
	const M365_CHAT_URL = "https://m365.cloud.microsoft/chat/";
	/** Clave de localStorage donde el interceptor del navegador acumula la captura. */
	const CAPTURE_STORE_KEY = "m365copilot.capture.v1";

//#endregion
//#region ../../packages/core/dist/jwt.js
/**
	* Decodifica el payload de un JWT sin validar la firma. Isomorfo: `atob` y
	* `TextDecoder` existen tanto en el navegador como en Node 18+, así que sirve
	* igual en el content script del navegador y en la extensión de VS Code.
	*/
	function decodeJwtPayload(token) {
		try {
			const part = String(token).split(".")[1];
			if (!part) return null;
			const b64 = part.replace(/-/g, "+").replace(/_/g, "/");
			const padded = b64.padEnd(Math.ceil(b64.length / 4) * 4, "=");
			const binary = atob(padded);
			const bytes = Uint8Array.from(binary, (ch) => ch.charCodeAt(0));
			return JSON.parse(new TextDecoder("utf-8").decode(bytes));
		} catch {
			return null;
		}
	}
	/** Extrae los claims relevantes, normalizando el nombre de usuario (upn). */
	function extractClaims(token) {
		const raw = decodeJwtPayload(token);
		if (!raw) return null;
		return {
			oid: typeof raw.oid === "string" ? raw.oid : void 0,
			tid: typeof raw.tid === "string" ? raw.tid : void 0,
			aud: typeof raw.aud === "string" ? raw.aud : void 0,
			exp: typeof raw.exp === "number" ? raw.exp : void 0,
			upn: typeof raw.upn === "string" && raw.upn || typeof raw.unique_name === "string" && raw.unique_name || typeof raw.preferred_username === "string" && raw.preferred_username || void 0
		};
	}

//#endregion
//#region ../../packages/core/dist/token.js
/** ¿Es un token de Substrate/Sydney, el que usa Copilot? */
	function isSydneyToken(token) {
		const claims = decodeJwtPayload(token);
		if (!claims) return false;
		const aud = String(claims.aud || "");
		const scp = String(claims.scp || claims.scope || "");
		return aud.includes("substrate.office.com") || aud.includes("substrate.svc.cloud.microsoft") || /sydney|m365chat/i.test(scp);
	}

//#endregion
//#region ../../packages/core/dist/capture.js
/** Un JWT de verdad no se acerca a esto; algo mayor no es un token. */
	const MAX_JWT_CHARS = 8192;
	/** Frames SignalR salientes que se llegan a inspeccionar. */
	const MAX_FRAME_CHARS = 1048576;
	/** Plantilla de invocación que merece la pena guardar. */
	const MAX_TEMPLATE_CHARS = 65536;
	const MAX_ENDPOINT_CHARS = 2048;
	/** Tres partes base64url y un tamaño razonable. */
	function isValidJwt(token) {
		if (typeof token !== "string" || token.length > 8192) return false;
		const parts = token.split(".");
		return parts.length === 3 && parts.every((part) => /^[A-Za-z0-9_-]+$/.test(part));
	}
	/** `exp` en el futuro y un `iat` coherente con él. */
	function areClaimsUsable(claims, now = Date.now()) {
		if (!claims || typeof claims.exp !== "number" || claims.exp <= 0) return false;
		if (claims.exp * 1e3 <= now) return false;
		const iat = claims.iat;
		if (iat !== void 0 && (typeof iat !== "number" || iat > claims.exp)) return false;
		return true;
	}
	/**
	* Lo que hay que guardar si `token` merece sustituir al actual, o null: debe
	* ser un JWT válido, de Substrate/Sydney (el de Copilot, no cualquier token de
	* Office), sin caducar, distinto del guardado y no más viejo que él.
	*/
	function acceptToken(current, token, now = Date.now()) {
		const candidate = token.trim();
		if (!isValidJwt(candidate) || !isSydneyToken(candidate)) return null;
		const claims = extractClaims(candidate);
		if (!claims || !areClaimsUsable(claims, now)) return null;
		if (current.accessToken === candidate) return null;
		const currentExp = current.claims?.exp ?? 0;
		if (claims.exp && currentExp && claims.exp < currentExp) return null;
		return {
			accessToken: candidate,
			claims
		};
	}
	/**
	* Tokens candidatos dentro de un valor de localStorage/sessionStorage: MSAL
	* guarda cada access token como JSON (`secret`), otras librerías como
	* `access_token`/`accessToken`, y algunas entradas son el JWT pelado.
	*/
	function tokensInStorageValue(value) {
		if (!value || value.length < 40 || !value.includes("eyJ")) return [];
		try {
			const parsed = JSON.parse(value);
			if (!parsed || typeof parsed !== "object") return [];
			return [
				parsed.secret,
				parsed.access_token,
				parsed.accessToken
			].filter((candidate) => typeof candidate === "string");
		} catch {
			const raw = value.trim();
			return /^ey[\w-]+\.[\w-]+\.[\w-]+$/.test(raw) ? [raw] : [];
		}
	}
	/** El token que viaja en la query de la URL del WebSocket, si lo hay. */
	function tokenInSocketUrl(url) {
		try {
			return new URL(String(url).replace(/^ws/i, "http")).searchParams.get("access_token");
		} catch {
			return null;
		}
	}
	/** ¿Es un socket de Substrate/Chathub (y no presencia, notificaciones…)? */
	function isCopilotSocketUrl(url) {
		const raw = String(url);
		return /chathub/i.test(raw) || /substrate/i.test(raw);
	}
	/**
	* Dominios de Microsoft desde los que se acepta un endpoint. El hub del chat
	* vive en `substrate.office.com`: la versión anterior sólo admitía
	* `.microsoft.com`/`.microsoft`, así que lo descartaba y el popup se quedaba
	* con «Endpoint: pendiente» para siempre.
	*/
	const MICROSOFT_HOST_SUFFIXES = [
		".office.com",
		".office.net",
		".microsoft.com",
		".microsoft",
		".cloud.microsoft"
	];
	function isMicrosoftHost(hostname) {
		const host = hostname.toLowerCase();
		return MICROSOFT_HOST_SUFFIXES.some((suffix) => host === suffix.slice(1) || host.endsWith(suffix));
	}
	/**
	* La URL del socket sin lo volátil (token, ids de sesión): no hay que guardar
	* un token caducado dentro del endpoint. '' si no es un host de Microsoft.
	*/
	function normalizeEndpoint(raw) {
		if (typeof raw !== "string" || raw.length > MAX_ENDPOINT_CHARS) return "";
		try {
			const url = new URL(raw.replace(/^ws/i, "http"));
			if (!isMicrosoftHost(url.hostname)) return "";
			for (const param of [
				"access_token",
				"ConversationId",
				"chatsessionid",
				"clientrequestid",
				"X-SessionId"
			]) url.searchParams.delete(param);
			return url.toString().replace(/^http/i, "ws");
		} catch {
			return "";
		}
	}
	/** SignalR separa los frames con este carácter (record separator). */
	const RS = "";
	/**
	* Mira un envío saliente por el socket: ¿lleva la invocación `chat` (prueba de
	* que es el hub del chat)? Si la lleva, devuelve también su plantilla.
	*/
	function inspectOutgoingFrames(data) {
		if (typeof data !== "string" || data.length > 1048576) return { sawChat: false };
		let found = { sawChat: false };
		for (const chunk of data.split(RS)) {
			if (!chunk) continue;
			let frame;
			try {
				frame = JSON.parse(chunk);
			} catch {
				continue;
			}
			if (frame.type !== 4 && frame.type !== 1 || frame.target !== "chat") continue;
			found = { sawChat: true };
			const args = Array.isArray(frame.arguments) ? frame.arguments[0] : null;
			if (args && typeof args === "object" && JSON.stringify(args).length <= 65536) found = {
				sawChat: true,
				template: args,
				invocationType: frame.type
			};
		}
		return found;
	}
	/** Un `tone` con forma de identificador de modelo de BizChat (p. ej. `Gpt_5_6_Reasoning`). */
	const TONE_PATTERN = /^[A-Za-z][A-Za-z0-9_.-]{1,63}$/;
	/** El `tone` (modelo) de una plantilla de invocación `chat`, si es válido. */
	function toneOfTemplate(template) {
		const tone = template?.tone;
		return typeof tone === "string" && TONE_PATTERN.test(tone) ? tone : null;
	}
	/**
	* `tones` con `tone` añadido como el más reciente (sin duplicados, acotado).
	* Así M365 puede estrenar un modelo y VS Code enterarse sin publicar versión:
	* en cuanto alguien lo usa en la web, la captura lo trae.
	*/
	function withObservedTone(tones, tone) {
		const list = (tones ?? []).filter((item) => item !== tone);
		if (tone) list.push(tone);
		return list.slice(-20);
	}
	/** El store sin el token si éste ya caducó (para invitar a recapturarlo), o null si no hay que tocarlo. */
	function withoutExpiredToken(store, now = Date.now()) {
		const exp = store.claims?.exp;
		if (!store.accessToken || typeof exp !== "number" || exp * 1e3 > now) return null;
		const cleaned = { ...store };
		delete cleaned.accessToken;
		delete cleaned.tokenSource;
		delete cleaned.claims;
		return cleaned;
	}
	/** Misma forma ignorando el sello temporal: sólo se escribe si algo cambió de verdad. */
	function sameCapture(a, b) {
		const strip = (store) => {
			const copy = { ...store };
			delete copy.capturedAt;
			return JSON.stringify(copy);
		};
		return strip(a) === strip(b);
	}
	/** El perfil que se envía a VS Code, o null si todavía no hay token. */
	function profileFromCapture(store, fallbackUserAgent) {
		if (!store.accessToken) return null;
		return {
			version: 1,
			capturedAt: store.capturedAt || (/* @__PURE__ */ new Date()).toISOString(),
			accessToken: store.accessToken,
			endpoint: store.endpoint || null,
			origin: store.origin || "https://m365.cloud.microsoft",
			userAgent: store.userAgent || fallbackUserAgent,
			invocationTemplate: store.invocationTemplate || null,
			invocationType: store.invocationType || 4,
			claims: store.claims || null,
			...store.observedTones && store.observedTones.length > 0 ? { observedTones: [...store.observedTones] } : {}
		};
	}
	/** Sin token: insistir. Con token fresco: vigilar de lejos. Cerca de caducar: apretar. */
	const SCAN_MISSING_MS = 2e3;
	const SCAN_MISSING_MAX_MS = 15e3;
	const SCAN_FRESH_MS = 6e4;
	const SCAN_EXPIRING_MS = 5e3;
	/** A partir de aquí la web ya suele haber renovado su propio token. */
	const EXPIRY_WATCH_MS = 9e5;
	/**
	* Cuándo volver a escanear la caché de MSAL. Se escanea SIEMPRE, haya token o
	* no: el token nuevo que la web renueva sola cada ~50 min sólo se recoge así.
	*/
	function nextScan(store, missingDelay, now = Date.now()) {
		if (!store.accessToken) {
			const grown = Math.min(Math.round(missingDelay * 1.5), SCAN_MISSING_MAX_MS);
			return {
				delay: grown,
				missingDelay: grown
			};
		}
		const exp = store.claims?.exp;
		const left = typeof exp === "number" ? exp * 1e3 - now : null;
		return {
			delay: left !== null && left <= 9e5 ? SCAN_EXPIRING_MS : SCAN_FRESH_MS,
			missingDelay: SCAN_MISSING_MS
		};
	}

//#endregion
//#region ../../packages/core/dist/sync.js
/** No martillear al servidor local de VS Code cuando está apagado. */
	const RESYNC_COOLDOWN_MS = 3e4;
	/**
	* ¿Hay que (re)enviar el perfil a VS Code? Cubre el caso más molesto: VS Code
	* arranca DESPUÉS de que el navegador capturara el token, y sin esto nadie se lo
	* vuelve a mandar hasta que el token cambia.
	*/
	function needsResync(context) {
		if (!context.hasToken) return false;
		if (context.lastSyncAttemptAt !== null && context.now - context.lastSyncAttemptAt >= 0 && context.now - context.lastSyncAttemptAt < 3e4) return false;
		if (context.syncedTokenExp === null) return true;
		if (context.currentTokenExp === null) return true;
		return context.currentTokenExp > context.syncedTokenExp;
	}

//#endregion
//#region ../../packages/core/dist/connectionArt.js
/**
	* Ilustración «M365 → VS Code» del popup de la extensión de navegador y del
	* panel del userscript: el logo de M365 Copilot a la izquierda, el de VS Code
	* a la derecha y una flecha entre ambos por la que viaja el token.
	*
	* - waiting:   los dos logos apagados (en gris); M365 «respira» mientras busca el token.
	* - captured:  M365 se enciende y el token espera en la salida de la flecha;
	*              VS Code sigue apagado (no responde).
	* - connected: VS Code se enciende con un halo, la flecha fluye y el token
	*              viaja hasta él una y otra vez.
	* - warning:   token caducado o hace falta iniciar sesión: aviso sobre M365.
	*
	* Los logos son los del proyecto (extensiones/vscode/logo/m365-vscode.svg y
	* vscode.svg), incrustados aquí como <symbol>. Ojo: el icono de VS Code es una
	* marca de Microsoft y sus pautas de uso restringen usarlo en extensiones o
	* en versiones modificadas; su uso aquí es decisión del proyecto.
	*
	* El SVG es estático y lleva su propio <style>: el estado se cambia SÓLO con el
	* atributo `data-state` de un ancestro, así el DOM no se recrea y los cambios
	* de estado se ven como transiciones (VS Code «se enciende» con un fundido).
	* El gris es un filtro de desaturación sobre el propio logo. Sin `vscode`,
	* `window` ni React: es una cadena que cualquiera puede insertar.
	*/
	function connectionState(input) {
		if (input.needsUser || input.hasToken && input.expired) return "warning";
		if (!input.hasToken) return "waiting";
		return input.vscodeConnected ? "connected" : "captured";
	}
	/** Logo de M365 Copilot del proyecto (logo/m365-vscode.svg): sus gradientes (fuera del
	* <symbol>, por compatibilidad) y el símbolo, con los ids prefijados. */
	function m365Symbol(id) {
		return `<radialGradient id="${id("m0")}" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(59.4363 31.0868) rotate(-130.285) scale(27.6431 26.1575)"><stop offset="0.0955758" stop-color="#00AEFF"/><stop offset="0.773185" stop-color="#2253CE"/><stop offset="1" stop-color="#0736C4"/></radialGradient>
<radialGradient id="${id("m1")}" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(15.3608 50.9716) rotate(50.2556) scale(25.0142 24.5538)"><stop stop-color="#FFB657"/><stop offset="0.633728" stop-color="#FF5F3D"/><stop offset="0.923392" stop-color="#C02B3C"/></radialGradient>
<linearGradient id="${id("m2")}" x1="17.6789" y1="10.6669" x2="21.2461" y2="52.961" gradientUnits="userSpaceOnUse"><stop offset="0.156162" stop-color="#0D91E1"/><stop offset="0.487484" stop-color="#52B471"/><stop offset="0.652394" stop-color="#98BD42"/><stop offset="0.937361" stop-color="#FFC800"/></linearGradient>
<linearGradient id="${id("m3")}" x1="20.9521" y1="5.07764" x2="22.8995" y2="51.2097" gradientUnits="userSpaceOnUse"><stop stop-color="#3DCBFF"/><stop offset="0.246674" stop-color="#0588F7" stop-opacity="0"/></linearGradient>
<radialGradient id="${id("m4")}" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(64.843 17.441) rotate(109.722) scale(61.4524 75.0539)"><stop offset="0.0661714" stop-color="#8C48FF"/><stop offset="0.5" stop-color="#F2598A"/><stop offset="0.895833" stop-color="#FFB152"/></radialGradient>
<linearGradient id="${id("m5")}" x1="66.9168" y1="19.1407" x2="66.8913" y2="31.7025" gradientUnits="userSpaceOnUse"><stop offset="0.0581535" stop-color="#F8ADFA"/><stop offset="0.708063" stop-color="#A86EDD" stop-opacity="0"/></linearGradient>
<symbol id="${id("m365")}" viewBox="0.5 0.578 72 72">
<path d="M53.1574 10.3146C52.1706 7.19669 49.2773 5.07764 46.007 5.07764L43.5352 5.07764C39.9228 5.07764 36.8237 7.65268 36.1621 11.2039L32.4891 30.9179L33.5912 27.2788C34.5491 24.1158 37.4644 21.9526 40.7692 21.9526H52.2499L58.8326 24.2562L62.3337 21.9644C59.0634 21.9644 56.1701 19.8336 55.1833 16.7157L53.1574 10.3146Z" fill="url(#${id("m0")})"/>
<path d="M20.615 62.8082C21.5914 65.9426 24.4927 68.0777 27.7757 68.0777H32.6415C36.7421 68.0777 40.0824 64.7845 40.1408 60.6844L40.3984 42.5737L39.4114 45.86C38.459 49.0313 35.5396 51.2027 32.2284 51.2027H20.75L14.8141 48.4965L11.4807 51.2027C14.7636 51.2027 17.665 53.3378 18.6414 56.4722L20.615 62.8082Z" fill="url(#${id("m1")})"/>
<path d="M45.5 5.07764H19.25C11.75 5.07764 7.25001 14.7496 4.25002 24.4216C0.695797 35.8804 -3.95498 51.2056 9.50001 51.2056H20.931C24.2656 51.2056 27.1975 49.0121 28.135 45.812C30.1073 39.0797 33.5545 27.3661 36.2631 18.446C37.6417 13.906 38.79 10.007 40.5523 7.57888C41.5404 6.21761 43.1871 5.07764 45.5 5.07764Z" fill="url(#${id("m2")})"/>
<path d="M45.5 5.07764H19.25C11.75 5.07764 7.25001 14.7496 4.25002 24.4216C0.695797 35.8804 -3.95498 51.2056 9.50001 51.2056H20.931C24.2656 51.2056 27.1975 49.0121 28.135 45.812C30.1073 39.0797 33.5545 27.3661 36.2631 18.446C37.6417 13.906 38.79 10.007 40.5523 7.57888C41.5404 6.21761 43.1871 5.07764 45.5 5.07764Z" fill="url(#${id("m3")})"/>
<path d="M27.4946 68.0776H53.7446C61.2446 68.0776 65.7446 58.4071 68.7446 48.7365C72.2988 37.2794 76.9496 21.9565 63.4946 21.9565H52.0633C48.7288 21.9565 45.797 24.1499 44.8594 27.3499C42.8871 34.0812 39.44 45.7927 36.7314 54.7113C35.3529 59.2506 34.2046 63.149 32.4422 65.5768C31.4542 66.9378 29.8075 68.0776 27.4946 68.0776Z" fill="url(#${id("m4")})"/>
<path d="M27.4946 68.0776H53.7446C61.2446 68.0776 65.7446 58.4071 68.7446 48.7365C72.2988 37.2794 76.9496 21.9565 63.4946 21.9565H52.0633C48.7288 21.9565 45.797 24.1499 44.8594 27.3499C42.8871 34.0812 39.44 45.7927 36.7314 54.7113C35.3529 59.2506 34.2046 63.149 32.4422 65.5768C31.4542 66.9378 29.8075 68.0776 27.4946 68.0776Z" fill="url(#${id("m5")})"/>
<rect x="24.125" y="51.2031" width="48.375" height="21.375" rx="3.63727" fill="black"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M27.0683 55.2876V68.3192H29.479V58.9306L32.1221 64.1367H33.7293L36.3143 58.9266V68.3192H38.8025V55.2876H36.0239L33.0046 61.3343L30.0019 55.2876H27.0683ZM45.0813 68.4839C43.6484 68.4839 42.5317 68.1418 41.7314 67.4576C40.9375 66.7734 40.5405 65.7439 40.5405 64.3691H42.9222C42.9222 65.021 43.1094 65.5309 43.4838 65.8988C43.8646 66.2668 44.3939 66.4507 45.0716 66.4507C45.6783 66.4507 46.143 66.2958 46.4657 65.986C46.7949 65.6762 46.9595 65.1856 46.9595 64.5144C46.9595 63.8689 46.7594 63.401 46.3592 63.1105C45.9655 62.8136 45.4524 62.6652 44.8198 62.6652H44.0356V60.7095H44.8876C45.4556 60.7095 45.9074 60.5546 46.2431 60.2447C46.5787 59.9349 46.7465 59.5251 46.7465 59.0152C46.7465 58.4988 46.5948 58.118 46.2915 57.8727C45.9946 57.6274 45.5847 57.5048 45.0619 57.5048C44.4874 57.5048 44.0421 57.6662 43.7258 57.9889C43.4095 58.3052 43.2514 58.7408 43.2514 59.2959H40.8794C40.8794 58.4246 41.0601 57.7081 41.4216 57.1466C41.7895 56.5851 42.2897 56.1655 42.9222 55.888C43.5548 55.604 44.2648 55.462 45.0522 55.462C45.7816 55.462 46.4561 55.5814 47.0757 55.8202C47.6953 56.059 48.1923 56.4237 48.5667 56.9142C48.9475 57.4048 49.1379 58.0341 49.1379 58.8022C49.1379 59.5832 48.9507 60.2028 48.5763 60.661C48.2084 61.1193 47.7114 61.442 47.0854 61.6292C47.776 61.7712 48.3472 62.0939 48.799 62.5974C49.2573 63.0944 49.4864 63.7947 49.4864 64.6983C49.4864 65.9247 49.0895 66.8638 48.2956 67.5157C47.5081 68.1611 46.4367 68.4839 45.0813 68.4839ZM52.875 67.8448C53.5914 68.2773 54.4047 68.4935 55.3148 68.4935C56.2313 68.4935 57.0058 68.3128 57.6384 67.9513C58.2774 67.5899 58.7614 67.0929 59.0906 66.4603C59.4198 65.8213 59.5844 65.0887 59.5844 64.2626C59.5844 63.4041 59.423 62.6845 59.1003 62.1036C58.7776 61.5162 58.3387 61.0741 57.7836 60.7772C57.235 60.4738 56.6153 60.3221 55.9247 60.3221C55.3438 60.3221 54.8339 60.4157 54.395 60.6029C53.9625 60.7901 53.5785 61.0386 53.2429 61.3484C53.2007 61.388 53.1589 61.4283 53.1174 61.4691C53.1613 60.2186 53.3483 59.2715 53.6785 58.6278C54.0658 57.8791 54.6144 57.5047 55.3244 57.5047C55.7633 57.5047 56.1183 57.6274 56.3894 57.8727C56.667 58.1115 56.8541 58.4761 56.951 58.9667H59.3327C59.1648 57.8436 58.7389 56.9819 58.0547 56.3817C57.3705 55.7749 56.4604 55.4716 55.3244 55.4716C54.4015 55.4716 53.5817 55.7072 52.8653 56.1784C52.1488 56.6431 51.5873 57.3627 51.1807 58.3374C50.774 59.3055 50.5707 60.548 50.5707 62.0648C50.5707 63.5881 50.7773 64.8241 51.1904 65.7729C51.6034 66.7153 52.165 67.4059 52.875 67.8448ZM53.1251 63.3296C53.2967 63.1623 53.4877 63.0086 53.6979 62.8684C54.2207 62.5134 54.8113 62.3359 55.4697 62.3359C55.9667 62.3359 56.3539 62.5102 56.6315 62.8587C56.909 63.2008 57.0478 63.6784 57.0478 64.2916C57.0478 64.9177 56.9026 65.4373 56.6121 65.8504C56.3281 66.2635 55.8957 66.47 55.3148 66.47C54.9404 66.47 54.5822 66.3506 54.2401 66.1118C53.9045 65.8665 53.6301 65.4696 53.4171 64.9209C53.2601 64.4988 53.1627 63.9683 53.1251 63.3296ZM62.9053 68.0676C63.583 68.3516 64.3382 68.4935 65.1708 68.4935C65.997 68.4935 66.7393 68.329 67.3976 67.9998C68.0624 67.6706 68.5885 67.1801 68.9757 66.5282C69.363 65.8698 69.5566 65.0469 69.5566 64.0593C69.5566 63.0718 69.3727 62.2747 69.0048 61.6679C68.6433 61.0612 68.1689 60.6191 67.5816 60.3416C66.9942 60.0576 66.3649 59.9156 65.6936 59.9156C65.1773 59.9156 64.7287 59.9995 64.3479 60.1673C63.9735 60.3286 63.6895 60.5191 63.4959 60.7385L63.7283 57.7565H68.5788V55.6362H61.7241L61.1723 62.6555H63.3894C63.5701 62.4296 63.7993 62.2424 64.0768 62.0939C64.3543 61.9455 64.6932 61.8713 65.0934 61.8713C65.6614 61.8713 66.1229 62.0455 66.4779 62.3941C66.8393 62.7362 67.02 63.2912 67.02 64.0593C67.02 64.892 66.849 65.5019 66.5069 65.8892C66.1713 66.2764 65.7259 66.4701 65.1708 66.4701C64.5835 66.4701 64.1026 66.3055 63.7283 65.9763C63.3539 65.6407 63.1667 65.1824 63.1667 64.6015H60.6979C60.6979 65.4729 60.8947 66.199 61.2885 66.7799C61.6886 67.3543 62.2276 67.7836 62.9053 68.0676Z" fill="white"/>
</symbol>`;
	}
	/** Logo de VS Code del proyecto (logo/vscode.svg). */
	function vscodeSymbol(id) {
		return `<symbol id="${id("vscode")}" viewBox="1.5 1.5 29 29">
<path d="M29.01,5.03,23.244,2.254a1.742,1.742,0,0,0-1.989.338L2.38,19.8A1.166,1.166,0,0,0,2.3,21.447c.025.027.05.053.077.077l1.541,1.4a1.165,1.165,0,0,0,1.489.066L28.142,5.75A1.158,1.158,0,0,1,30,6.672V6.605A1.748,1.748,0,0,0,29.01,5.03Z" fill="#0065a9"/>
<path d="M29.01,26.97l-5.766,2.777a1.745,1.745,0,0,1-1.989-.338L2.38,12.2A1.166,1.166,0,0,1,2.3,10.553c.025-.027.05-.053.077-.077l1.541-1.4A1.165,1.165,0,0,1,5.41,9.01L28.142,26.25A1.158,1.158,0,0,0,30,25.328V25.4A1.749,1.749,0,0,1,29.01,26.97Z" fill="#007acc"/>
<path d="M23.244,29.747a1.745,1.745,0,0,1-1.989-.338A1.025,1.025,0,0,0,23,28.684V3.316a1.024,1.024,0,0,0-1.749-.724,1.744,1.744,0,0,1,1.989-.339l5.765,2.772A1.748,1.748,0,0,1,30,6.6V25.4a1.748,1.748,0,0,1-.991,1.576Z" fill="#1f9cf0"/>
</symbol>`;
	}
	/** Marcado del SVG; el estado lo decide `data-state` en un elemento que lo contenga. */
	function connectionArtSvg(options = {}) {
		const id = (name) => `${options.idPrefix ?? "m365art"}-${name}`;
		const left = escapeXml(options.leftLabel ?? "M365 Copilot");
		const right = escapeXml(options.rightLabel ?? "VS Code");
		const title = escapeXml(options.title ?? `${options.leftLabel ?? "M365 Copilot"} → ${options.rightLabel ?? "VS Code"}`);
		const use = (symbol, extra = "") => `<use href="#${id(symbol)}" xlink:href="#${id(symbol)}" width="64" height="64"${extra}/>`;
		return `<svg class="m365-art" viewBox="0 0 260 104" role="img" aria-label="${title}" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<title>${title}</title>
<defs>
  ${m365Symbol(id)}
  ${vscodeSymbol(id)}
  <linearGradient id="${id("flow")}" x1="90" y1="0" x2="168" y2="0" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="#b267ff"/><stop offset="1" stop-color="#1f9cf0"/>
  </linearGradient>
  <filter id="${id("grey")}" color-interpolation-filters="sRGB"><feColorMatrix type="saturate" values="0"/></filter>
  <filter id="${id("blur")}" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="6"/></filter>
</defs>
<style>
  .m365-art { display: block; width: 100%; height: auto; overflow: visible; }
  .m365-art .layer, .m365-art .badge, .m365-art .wire, .m365-art .dot { transition: opacity .6s ease; }
  .m365-art .on, .m365-art .badge, .m365-art .flow, .m365-art .warnwire, .m365-art .dot, .m365-art .halo { opacity: 0; }
  .m365-art .off { opacity: .38; }
  .m365-art .track { stroke: currentColor; stroke-opacity: .35; stroke-width: 3; stroke-dasharray: 1 8; stroke-linecap: round; fill: none; }
  .m365-art .flow { stroke: url(#${id("flow")}); stroke-width: 4; stroke-dasharray: 12 8; stroke-linecap: round; fill: none; animation: m365-art-flow .9s linear infinite; }
  .m365-art .warnwire { stroke: #d29922; stroke-width: 3; stroke-dasharray: 6 6; fill: none; }
  .m365-art .head { fill: none; stroke: currentColor; stroke-opacity: .35; stroke-width: 3.5; stroke-linecap: round; stroke-linejoin: round; transition: stroke .6s ease, stroke-opacity .6s ease; }
  .m365-art .label { fill: currentColor; opacity: .7; font: 600 11px -apple-system, 'Segoe UI', system-ui, sans-serif; text-anchor: middle; }
  .m365-art .dot circle { fill: #fff; stroke: url(#${id("flow")}); stroke-width: 3; }
  [data-state="waiting"] .m365-art .m365 .off { animation: m365-art-breathe 2.4s ease-in-out infinite; }
  [data-state="captured"] .m365-art .m365 .on,
  [data-state="connected"] .m365-art .m365 .on,
  [data-state="warning"] .m365-art .m365 .on { opacity: 1; }
  [data-state="captured"] .m365-art .m365 .off,
  [data-state="connected"] .m365-art .m365 .off,
  [data-state="warning"] .m365-art .m365 .off,
  [data-state="connected"] .m365-art .vscode .off { opacity: 0; }
  [data-state="captured"] .m365-art .dot { opacity: 1; }
  [data-state="captured"] .m365-art .dot circle { animation: m365-art-ready 1.4s ease-in-out infinite; transform-origin: 96px 46px; }
  [data-state="connected"] .m365-art .vscode .on,
  [data-state="connected"] .m365-art .flow,
  [data-state="connected"] .m365-art .badge.ok { opacity: 1; }
  [data-state="connected"] .m365-art .halo { opacity: .6; animation: m365-art-glow 2.6s ease-in-out infinite; }
  [data-state="connected"] .m365-art .head { stroke: #1f9cf0; stroke-opacity: 1; }
  [data-state="connected"] .m365-art .dot { opacity: 1; animation: m365-art-travel 1.8s cubic-bezier(.45,0,.55,1) infinite; }
  [data-state="warning"] .m365-art .warnwire,
  [data-state="warning"] .m365-art .badge.warn { opacity: 1; }
  [data-state="warning"] .m365-art .track,
  [data-state="connected"] .m365-art .track { opacity: 0; }
  @keyframes m365-art-flow { to { stroke-dashoffset: -20; } }
  @keyframes m365-art-breathe { 0%, 100% { opacity: .28; } 50% { opacity: .6; } }
  @keyframes m365-art-ready { 0%, 100% { transform: scale(.75); } 50% { transform: scale(1.1); } }
  @keyframes m365-art-glow { 0%, 100% { opacity: .3; } 50% { opacity: .75; } }
  @keyframes m365-art-travel {
    0% { transform: translateX(0); opacity: 0; } 12% { opacity: 1; }
    80% { transform: translateX(62px); opacity: 1; } 100% { transform: translateX(68px); opacity: 0; }
  }
  @media (prefers-reduced-motion: reduce) {
    .m365-art *, .m365-art { animation: none !important; transition: none !important; }
    [data-state="connected"] .m365-art .dot { transform: translateX(62px); }
  }
</style>
<g class="node m365" transform="translate(14 14)">
  <g class="layer off" filter="url(#${id("grey")})">${use("m365")}</g>
  <g class="layer on">${use("m365")}</g>
  <g class="badge warn" transform="translate(62 2)"><circle r="10" fill="#d29922"/><path d="M0 -5V1.5M0 5.2V5.4" stroke="#fff" stroke-width="3" stroke-linecap="round"/></g>
</g>
<path class="track wire" d="M92 46H162"/>
<path class="flow wire" d="M92 46H162"/>
<path class="warnwire wire" d="M92 46H162"/>
<path class="head" d="M160 38L169 46L160 54"/>
<g class="dot"><circle cx="98" cy="46" r="5.5"/></g>
<g class="node vscode" transform="translate(182 14)">
  <g class="halo" filter="url(#${id("blur")})">${use("vscode")}</g>
  <g class="layer off" filter="url(#${id("grey")})">${use("vscode")}</g>
  <g class="layer on">${use("vscode")}</g>
  <g class="badge ok" transform="translate(62 2)"><circle r="10" fill="#2ea043"/><path d="M-4.5 0.5L-1.2 3.8L4.8 -3" fill="none" stroke="#fff" stroke-width="2.8" stroke-linecap="round" stroke-linejoin="round"/></g>
</g>
<text class="label" x="46" y="98">${left}</text>
<text class="label" x="214" y="98">${right}</text>
</svg>`;
	}
	function escapeXml(text) {
		return text.replace(/[<>&"']/g, (char) => `&#${char.charCodeAt(0)};`);
	}

//#endregion
//#region userscript/main.ts
/**
	* M365 Copilot → VS Code, Tampermonkey/Violentmonkey userscript.
	*
	* The alternative to the browser extension, with the same behaviour: it
	* captures the Copilot (Substrate/Sydney) token from the page — the WebSocket
	* URL, request headers and the MSAL cache — keeps scanning so the token the
	* web app renews by itself every ~50 min is picked up, and SENDS it to the VS
	* Code extension's local server, so there is nothing to copy and paste.
	*
	* Every decision (which token to accept, which frame is the chat, when to scan
	* again, when to re-sync with VS Code) comes from `@m365copilot/core`, the
	* same code the browser extension runs. This file is bundled into
	* `../m365copilot-token.user.js` by scripts/build-userscript.mjs — edit this
	* one, never the generated file.
	*
	* State lives in GM storage, shared by every tab and frame where the script
	* runs: any frame can capture, the top-level frames sync and draw the panel.
	*/
	const SYNC_KEY = "m365copilot.sync.v1";
	const UI_KEY = "m365copilot.ui.v1";
	const HEALTH_EVERY_MS = 3e4;
	const REQUEST_TIMEOUT_MS = 4e3;
	/** Reload a hidden tab whose token expired at most this often (shared by all tabs). */
	const RELOAD_EVERY_MS = 6e5;
	/** Never reload a page that has been open for less than this (no reload loops). */
	const MIN_PAGE_AGE_MS = 12e4;
	const EMPTY_SYNC = {
		syncedTokenExp: null,
		lastSyncAttemptAt: null,
		lastSyncedAt: null,
		lastError: null,
		vscodeReachable: null,
		lastReloadAt: null,
		syncedTones: []
	};
	const PAGE = typeof unsafeWindow !== "undefined" ? unsafeWindow : window;
	const IS_TOP = (() => {
		try {
			return window.top === window.self;
		} catch {
			return false;
		}
	})();
	const LOADED_AT = Date.now();
	const TEXTS = {
		en: {
			title: "M365 Copilot → VS Code",
			art: "Connection between Microsoft 365 Copilot and VS Code",
			minimize: "Minimize",
			expand: "Show the M365 Copilot panel",
			close: "Hide until the next page load",
			waitingTitle: "Waiting for the token",
			waitingSub: "Send a message in the chat to capture it.",
			capturedTitle: "Token ready",
			capturedSub: "VS Code is not answering. Open it with the M365 Copilot extension enabled.",
			connectedTitle: "Connected to VS Code",
			connectedSub: "The token is sent automatically whenever it is renewed.",
			warningTitle: "Token expired",
			warningSub: "Reload this page or sign in again to renew it.",
			token: "Token",
			tokenNone: "not captured",
			tokenLeft: "{0} min left",
			tokenExpired: "expired",
			vscode: "VS Code",
			vscodeOk: "connected",
			vscodeDown: "not answering",
			vscodeChecking: "checking…",
			sync: "Last sync",
			syncNever: "never",
			syncJustNow: "just now",
			syncAgo: "{0} min ago",
			send: "Send to VS Code",
			sent: "✓ Sent",
			sendFailed: "VS Code did not answer",
			copyToken: "Copy token",
			copyProfile: "Copy profile",
			copied: "✓ Copied",
			renew: "Reload to renew",
			menuShow: "Show panel",
			menuSend: "Send token to VS Code now",
			menuAutoReloadOn: "Auto-renew: reload this tab when hidden and expired — currently ON",
			menuAutoReloadOff: "Auto-renew: reload this tab when hidden and expired — currently OFF",
			openM365: "Open M365 Copilot"
		},
		es: {
			title: "M365 Copilot → VS Code",
			art: "Conexión entre Microsoft 365 Copilot y VS Code",
			minimize: "Minimizar",
			expand: "Mostrar el panel de M365 Copilot",
			close: "Ocultar hasta la próxima carga de la página",
			waitingTitle: "Esperando el token",
			waitingSub: "Envía un mensaje en el chat para capturarlo.",
			capturedTitle: "Token listo",
			capturedSub: "VS Code no responde. Ábrelo con la extensión M365 Copilot activa.",
			connectedTitle: "Conectado con VS Code",
			connectedSub: "El token se envía solo cada vez que se renueva.",
			warningTitle: "Token caducado",
			warningSub: "Recarga esta página o vuelve a iniciar sesión para renovarlo.",
			token: "Token",
			tokenNone: "sin capturar",
			tokenLeft: "quedan {0} min",
			tokenExpired: "caducado",
			vscode: "VS Code",
			vscodeOk: "conectado",
			vscodeDown: "no responde",
			vscodeChecking: "comprobando…",
			sync: "Última sincronización",
			syncNever: "nunca",
			syncJustNow: "ahora mismo",
			syncAgo: "hace {0} min",
			send: "Enviar a VS Code",
			sent: "✓ Enviado",
			sendFailed: "VS Code no respondió",
			copyToken: "Copiar token",
			copyProfile: "Copiar perfil",
			copied: "✓ Copiado",
			renew: "Recargar para renovar",
			menuShow: "Mostrar el panel",
			menuSend: "Enviar el token a VS Code ahora",
			menuAutoReloadOn: "Auto-renovar: recargar esta pestaña oculta si caduca — ahora ACTIVADO",
			menuAutoReloadOff: "Auto-renovar: recargar esta pestaña oculta si caduca — ahora DESACTIVADO",
			openM365: "Abrir M365 Copilot"
		}
	};
	const T = /^es\b/i.test(navigator.language || "") ? TEXTS.es : TEXTS.en;
	const fill = (template, value) => template.replace("{0}", String(value));
	function readJson(key, fallback) {
		try {
			const raw = GM_getValue(key, "");
			return raw ? {
				...fallback,
				...JSON.parse(raw)
			} : fallback;
		} catch {
			return fallback;
		}
	}
	const readStore = () => readJson(CAPTURE_STORE_KEY, {});
	const readSync = () => readJson(SYNC_KEY, EMPTY_SYNC);
	const readUi = () => readJson(UI_KEY, {
		minimized: false,
		autoReload: true
	});
	const writeSync = (patch) => GM_setValue(SYNC_KEY, JSON.stringify({
		...readSync(),
		...patch
	}));
	const writeUi = (patch) => GM_setValue(UI_KEY, JSON.stringify({
		...readUi(),
		...patch
	}));
	/** Merge `patch` into the capture, writing only when something really changed. */
	function writeStore(patch) {
		const current = readStore();
		const merged = {
			...current,
			...patch
		};
		if (sameCapture(current, merged)) return current;
		merged.capturedAt = (/* @__PURE__ */ new Date()).toISOString();
		GM_setValue(CAPTURE_STORE_KEY, JSON.stringify(merged));
		return merged;
	}
	function pruneExpiredToken() {
		const cleaned = withoutExpiredToken(readStore());
		if (!cleaned) return;
		cleaned.capturedAt = (/* @__PURE__ */ new Date()).toISOString();
		GM_setValue(CAPTURE_STORE_KEY, JSON.stringify(cleaned));
	}
	function offerToken(token, source) {
		if (!token) return;
		try {
			const accepted = acceptToken(readStore(), token);
			if (!accepted) return;
			writeStore({
				...accepted,
				tokenSource: source
			});
			if (IS_TOP) syncToVSCode(hasUnsentChanges());
		} catch {}
	}
	function captureSocket(url, socket) {
		const raw = String(url);
		if (!isCopilotSocketUrl(raw)) return;
		offerToken(tokenInSocketUrl(raw), "websocket-url");
		const endpoint = normalizeEndpoint(raw);
		if (endpoint && !readStore().endpointConfirmed) writeStore({
			endpoint,
			origin: location.origin,
			userAgent: navigator.userAgent
		});
		const originalSend = socket.send;
		socket.send = function(...args) {
			try {
				const frames = inspectOutgoingFrames(args[0]);
				if (frames.sawChat) {
					const tone = toneOfTemplate(frames.template);
					writeStore({
						...tone ? { observedTones: withObservedTone(readStore().observedTones, tone) } : {},
						...endpoint ? {
							endpoint,
							endpointConfirmed: true
						} : {},
						origin: location.origin,
						userAgent: navigator.userAgent,
						...frames.template ? {
							invocationTemplate: frames.template,
							invocationType: frames.invocationType
						} : {}
					});
				}
			} catch {}
			return originalSend.apply(this, args);
		};
	}
	function headerValue(headers, name) {
		if (!headers) return null;
		try {
			const wanted = name.toLowerCase();
			if (typeof Headers !== "undefined" && headers instanceof Headers) return headers.get(name);
			if (Array.isArray(headers)) {
				const hit = headers.find((entry) => String(entry[0]).toLowerCase() === wanted);
				return hit ? String(hit[1]) : null;
			}
			for (const [key, value] of Object.entries(headers)) if (key.toLowerCase() === wanted) return String(value);
		} catch {}
		return null;
	}
	function offerBearer(value, source) {
		if (value && /^bearer /i.test(value)) offerToken(value.slice(7), source);
	}
	function installHooks() {
		if (PAGE.WebSocket) {
			const NativeWebSocket = PAGE.WebSocket;
			PAGE.WebSocket = new Proxy(NativeWebSocket, { construct(target, args) {
				const socket = Reflect.construct(target, args);
				try {
					captureSocket(args[0], socket);
				} catch {}
				return socket;
			} });
		}
		if (PAGE.fetch) {
			const nativeFetch = PAGE.fetch;
			PAGE.fetch = function(input, init) {
				try {
					let auth = headerValue(init?.headers, "authorization");
					if (!auth && typeof Request !== "undefined" && input instanceof Request) auth = input.headers.get("authorization");
					offerBearer(auth, "fetch-header");
				} catch {}
				return nativeFetch.call(this, input, init);
			};
		}
		if (PAGE.XMLHttpRequest) {
			const setHeader = PAGE.XMLHttpRequest.prototype.setRequestHeader;
			PAGE.XMLHttpRequest.prototype.setRequestHeader = function(name, value) {
				try {
					if (String(name).toLowerCase() === "authorization") offerBearer(String(value), "xhr-header");
				} catch {}
				return setHeader.call(this, name, value);
			};
		}
	}
	/** MSAL keeps access tokens in localStorage / sessionStorage. */
	function scanStorages() {
		for (const storeName of ["localStorage", "sessionStorage"]) {
			let store;
			let length = 0;
			try {
				store = PAGE[storeName];
				length = store.length;
			} catch {
				continue;
			}
			for (let index = 0; index < length; index += 1) try {
				const key = store.key(index);
				if (!key || key === "m365copilot.capture.v1") continue;
				for (const token of tokensInStorageValue(store.getItem(key))) offerToken(token, "msal-cache");
			} catch {}
		}
	}
	function request(method, path, body) {
		return new Promise((resolve) => {
			try {
				GM_xmlhttpRequest({
					method,
					url: `${TOKEN_SERVER_URL}${path}`,
					headers: body ? { "Content-Type": "application/json" } : void 0,
					data: body,
					timeout: REQUEST_TIMEOUT_MS,
					onload: (response) => resolve(response.status),
					onerror: () => resolve(0),
					ontimeout: () => resolve(0)
				});
			} catch {
				resolve(0);
			}
		});
	}
	let syncing = false;
	/**
	* The stored token is one VS Code has not received yet, and VS Code was not
	* down a moment ago: send it now instead of waiting out the re-sync cooldown,
	* which only exists not to hammer a VS Code that is not running.
	*/
	function hasUnsentToken() {
		const exp = readStore().claims?.exp;
		const sync = readSync();
		return typeof exp === "number" && (sync.syncedTokenExp === null || exp > sync.syncedTokenExp) && sync.vscodeReachable !== false;
	}
	/**
	* The web app used a model (`tone`) VS Code has not been told about. The chat
	* frame that reveals it arrives AFTER the token was sent, so without this VS
	* Code would only learn it at the next token renewal, ~50 min later.
	*/
	function hasUnsentTone() {
		const sync = readSync();
		return sync.vscodeReachable !== false && (readStore().observedTones ?? []).some((tone) => !sync.syncedTones.includes(tone));
	}
	const hasUnsentChanges = () => hasUnsentToken() || hasUnsentTone();
	/**
	* Send the profile to VS Code when it needs it: a token it does not have yet,
	* or VS Code started after the capture — the same rule (and cooldown) as the
	* browser extension. `force` is the panel's "Send to VS Code" button.
	*/
	async function syncToVSCode(force = false) {
		const store = readStore();
		const profile = profileFromCapture(store, navigator.userAgent);
		if (!profile || !areClaimsUsable(store.claims) || syncing) return false;
		const sync = readSync();
		const now = Date.now();
		if (!force && !needsResync({
			capturedAt: store.capturedAt ?? null,
			syncedTokenExp: sync.syncedTokenExp,
			currentTokenExp: store.claims?.exp ?? null,
			hasToken: true,
			lastSyncAttemptAt: sync.lastSyncAttemptAt,
			now
		})) return false;
		syncing = true;
		writeSync({ lastSyncAttemptAt: now });
		try {
			const status = await request("POST", TOKEN_ENDPOINT_PATH, JSON.stringify(profile));
			if (status >= 200 && status < 300) {
				writeSync({
					syncedTokenExp: store.claims?.exp ?? null,
					syncedTones: profile.observedTones ?? [],
					lastSyncedAt: Date.now(),
					lastError: null,
					vscodeReachable: true
				});
				return true;
			}
			writeSync({
				lastError: status ? `HTTP ${status}` : "unreachable",
				vscodeReachable: status !== 0
			});
			return false;
		} finally {
			syncing = false;
		}
	}
	async function checkHealth() {
		const status = await request("GET", HEALTH_ENDPOINT_PATH);
		const reachable = status >= 200 && status < 300;
		if (readSync().vscodeReachable !== reachable) writeSync({ vscodeReachable: reachable });
		if (reachable) await syncToVSCode();
	}
	/**
	* The page renews its own token while it is in use; a tab left in the
	* background can sit on an expired one. Reloading it (only while hidden, at
	* most every 10 min across tabs, never right after it loaded) makes MSAL
	* fetch a new one — the same last resort the browser extension uses.
	*/
	function maybeReloadToRenew() {
		if (!IS_TOP || !readUi().autoReload || document.visibilityState !== "hidden") return;
		const store = readStore();
		const hadSession = Boolean(store.endpoint || store.invocationTemplate);
		const expired = !store.accessToken || !areClaimsUsable(store.claims);
		if (!hadSession || !expired || Date.now() - LOADED_AT < MIN_PAGE_AGE_MS) return;
		const { lastReloadAt } = readSync();
		if (lastReloadAt && Date.now() - lastReloadAt < RELOAD_EVERY_MS) return;
		writeSync({ lastReloadAt: Date.now() });
		location.reload();
	}
	let missingDelay = SCAN_MISSING_MS;
	function tick() {
		try {
			scanStorages();
			pruneExpiredToken();
			maybeReloadToRenew();
		} catch {}
		const next = nextScan(readStore(), missingDelay);
		missingDelay = next.missingDelay;
		setTimeout(tick, next.delay);
	}
	const STYLE = `
:host { all: initial; }
.panel { position: fixed; right: 16px; bottom: 16px; z-index: 2147483647; width: 280px; box-sizing: border-box;
  padding: 12px 14px 14px; border-radius: 14px; background: #161b22; color: #e6edf3;
  border: 1px solid #30363d; box-shadow: 0 10px 30px rgba(0,0,0,.45);
  font: 12px/1.45 -apple-system, "Segoe UI", system-ui, sans-serif; }
.head { display: flex; align-items: center; justify-content: space-between; font-weight: 600; margin-bottom: 4px; }
.icons { display: flex; gap: 2px; }
.icon { cursor: pointer; background: none; border: 0; color: #9198a1; font-size: 14px; width: 24px; height: 24px; border-radius: 6px; }
.icon:hover { background: #21262d; color: #e6edf3; }
.art { color: #9198a1; margin: 2px 4px 6px; }
.status { text-align: center; margin-bottom: 8px; }
.status-title { font-weight: 600; font-size: 13px; }
.status-sub { color: #9198a1; font-size: 11.5px; }
[data-state="connected"] .status-title { color: #3fb950; }
[data-state="warning"] .status-title { color: #d29922; }
.rows { border: 1px solid #21262d; border-radius: 10px; padding: 2px 10px; margin-bottom: 10px; }
.row { display: flex; justify-content: space-between; gap: 8px; padding: 5px 0; }
.row + .row { border-top: 1px solid #21262d; }
.row-label { color: #9198a1; }
.row-value { font-variant-numeric: tabular-nums; }
.buttons { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; }
button.act { padding: 7px 10px; border: 0; border-radius: 8px; background: #1f6feb; color: #fff;
  font: 600 12px -apple-system, "Segoe UI", system-ui, sans-serif; cursor: pointer; }
button.act:hover:enabled { background: #388bfd; }
button.act:disabled { background: #30363d; color: #6e7681; cursor: not-allowed; }
button.wide { grid-column: 1 / -1; }
button.ghost { background: transparent; border: 1px solid #30363d; color: #c9d1d9; }
button.ghost:hover:enabled { background: #21262d; }
.mini { position: fixed; right: 16px; bottom: 16px; z-index: 2147483647; width: 132px; padding: 6px 8px 4px;
  border-radius: 12px; background: #161b22; border: 1px solid #30363d; box-shadow: 0 6px 18px rgba(0,0,0,.4);
  color: #9198a1; cursor: pointer; }
.mini:hover { border-color: #1f6feb; }
.hidden { display: none !important; }
@media (prefers-color-scheme: light) {
  .panel, .mini { background: #ffffff; color: #1f2328; border-color: #d1d9e0; box-shadow: 0 10px 30px rgba(31,35,40,.18); }
  .art, .status-sub, .row-label, .icon, .mini { color: #59636e; }
  .rows, .row + .row { border-color: #e4e8ec; }
  .icon:hover, button.ghost:hover:enabled { background: #f6f8fa; color: #1f2328; }
  button.ghost { border-color: #d1d9e0; color: #1f2328; }
  button.act:disabled { background: #eff2f5; color: #818b98; }
  [data-state="connected"] .status-title { color: #1a7f37; }
  [data-state="warning"] .status-title { color: #9a6700; }
}`;
	function mountUi() {
		if (!IS_TOP || document.getElementById("m365copilot-grabber")) return;
		const host = document.createElement("div");
		host.id = "m365copilot-grabber";
		const root = host.attachShadow ? host.attachShadow({ mode: "open" }) : host;
		const style = document.createElement("style");
		style.textContent = STYLE;
		const panel = document.createElement("div");
		panel.className = "panel";
		const mini = document.createElement("div");
		mini.className = "mini";
		panel.innerHTML = [
			"<div class=\"head\"><span data-text=\"title\"></span><span class=\"icons\">",
			"<button class=\"icon\" data-action=\"minimize\">–</button><button class=\"icon\" data-action=\"close\">✕</button></span></div>",
			`<div class="art">${connectionArtSvg({
				idPrefix: "us-art",
				title: T.art
			})}</div>`,
			"<div class=\"status\"><div class=\"status-title\"></div><div class=\"status-sub\"></div></div>",
			"<div class=\"rows\">",
			"<div class=\"row\"><span class=\"row-label\" data-text=\"token\"></span><span class=\"row-value\" data-value=\"token\"></span></div>",
			"<div class=\"row\"><span class=\"row-label\" data-text=\"vscode\"></span><span class=\"row-value\" data-value=\"vscode\"></span></div>",
			"<div class=\"row\"><span class=\"row-label\" data-text=\"sync\"></span><span class=\"row-value\" data-value=\"sync\"></span></div>",
			"</div>",
			"<div class=\"buttons\">",
			"<button class=\"act wide\" data-action=\"send\"></button>",
			"<button class=\"act ghost\" data-action=\"token\"></button>",
			"<button class=\"act ghost\" data-action=\"profile\"></button>",
			"</div>"
		].join("");
		mini.innerHTML = connectionArtSvg({
			idPrefix: "us-mini",
			title: T.expand
		});
		mini.title = T.expand;
		const q = (selector) => panel.querySelector(selector);
		for (const node of Array.from(panel.querySelectorAll("[data-text]"))) node.textContent = T[node.getAttribute("data-text")];
		q("[data-action=\"minimize\"]").title = T.minimize;
		q("[data-action=\"close\"]").title = T.close;
		const sendButton = q("[data-action=\"send\"]");
		const tokenButton = q("[data-action=\"token\"]");
		const profileButton = q("[data-action=\"profile\"]");
		tokenButton.textContent = T.copyToken;
		profileButton.textContent = T.copyProfile;
		root.appendChild(style);
		root.appendChild(panel);
		root.appendChild(mini);
		(document.body || document.documentElement).appendChild(host);
		const flash = (button, text, restore) => {
			button.textContent = text;
			setTimeout(restore, 1600);
		};
		function render() {
			const store = readStore();
			const sync = readSync();
			const hasToken = Boolean(store.accessToken);
			const usable = hasToken && areClaimsUsable(store.claims);
			const state = connectionState({
				hasToken,
				expired: hasToken && !usable,
				vscodeConnected: sync.vscodeReachable === true
			});
			panel.dataset.state = state;
			mini.dataset.state = state;
			const { minimized } = readUi();
			panel.classList.toggle("hidden", minimized);
			mini.classList.toggle("hidden", !minimized);
			const [title, sub] = {
				waiting: [T.waitingTitle, T.waitingSub],
				captured: [T.capturedTitle, T.capturedSub],
				connected: [T.connectedTitle, T.connectedSub],
				warning: [T.warningTitle, T.warningSub]
			}[state];
			q(".status-title").textContent = title;
			q(".status-sub").textContent = sub;
			const exp = store.claims?.exp;
			const minutes = typeof exp === "number" ? Math.round((exp * 1e3 - Date.now()) / 6e4) : null;
			q("[data-value=\"token\"]").textContent = !hasToken ? T.tokenNone : !usable ? T.tokenExpired : minutes === null ? "✓" : fill(T.tokenLeft, minutes);
			q("[data-value=\"vscode\"]").textContent = sync.vscodeReachable === null ? T.vscodeChecking : sync.vscodeReachable ? T.vscodeOk : T.vscodeDown;
			const ago = sync.lastSyncedAt ? Math.floor((Date.now() - sync.lastSyncedAt) / 6e4) : null;
			q("[data-value=\"sync\"]").textContent = ago === null ? T.syncNever : ago < 1 ? T.syncJustNow : fill(T.syncAgo, ago);
			if (!sendButton.dataset.flashing) sendButton.textContent = state === "warning" ? T.renew : T.send;
			sendButton.disabled = !hasToken && state !== "warning";
			tokenButton.disabled = !usable;
			profileButton.disabled = !usable;
		}
		q("[data-action=\"close\"]").addEventListener("click", () => host.remove());
		q("[data-action=\"minimize\"]").addEventListener("click", () => {
			writeUi({ minimized: true });
			render();
		});
		mini.addEventListener("click", () => {
			writeUi({ minimized: false });
			render();
		});
		sendButton.addEventListener("click", async () => {
			if (panel.dataset.state === "warning") {
				location.reload();
				return;
			}
			sendButton.dataset.flashing = "1";
			const ok = await syncToVSCode(true);
			render();
			flash(sendButton, ok ? T.sent : T.sendFailed, () => {
				delete sendButton.dataset.flashing;
				render();
			});
		});
		tokenButton.addEventListener("click", () => {
			const token = readStore().accessToken;
			if (!token || !copy(token)) return;
			flash(tokenButton, T.copied, () => tokenButton.textContent = T.copyToken);
		});
		profileButton.addEventListener("click", () => {
			const profile = profileFromCapture(readStore(), navigator.userAgent);
			if (!profile || !copy(JSON.stringify(profile, null, 2))) return;
			flash(profileButton, T.copied, () => profileButton.textContent = T.copyProfile);
		});
		render();
		for (const key of [
			CAPTURE_STORE_KEY,
			SYNC_KEY,
			UI_KEY
		]) try {
			GM_addValueChangeListener(key, () => render());
		} catch {}
		setInterval(render, 15e3);
	}
	function copy(text) {
		try {
			GM_setClipboard(text, "text");
			return true;
		} catch {
			try {
				navigator.clipboard.writeText(text);
				return true;
			} catch {
				return false;
			}
		}
	}
	function registerMenu() {
		if (!IS_TOP) return;
		try {
			GM_registerMenuCommand(T.menuShow, () => writeUi({ minimized: false }));
			GM_registerMenuCommand(T.menuSend, () => void syncToVSCode(true));
			GM_registerMenuCommand(readUi().autoReload ? T.menuAutoReloadOn : T.menuAutoReloadOff, () => writeUi({ autoReload: !readUi().autoReload }));
			GM_registerMenuCommand(T.openM365, () => window.open(M365_CHAT_URL, "_blank"));
		} catch {}
	}
	installHooks();
	scanStorages();
	setTimeout(tick, missingDelay);
	for (const [target, event] of [
		[document, "visibilitychange"],
		[window, "focus"],
		[PAGE, "storage"]
	]) target.addEventListener(event, () => {
		if (event === "visibilitychange" && document.visibilityState !== "visible") return;
		try {
			scanStorages();
		} catch {}
	});
	if (IS_TOP) {
		registerMenu();
		try {
			GM_addValueChangeListener(CAPTURE_STORE_KEY, () => void syncToVSCode(hasUnsentChanges()));
		} catch {}
		checkHealth();
		setInterval(() => void checkHealth(), HEALTH_EVERY_MS);
		if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", mountUi, { once: true });
		else mountUi();
	}

//#endregion
})();